name: Test workflow

on:
  push:
    branches:
      - dev
    branches-ignore:
      - staging

jobs:
  echo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo the name
        run: |
          export NAME=Raphael
          echo the $NAME